import { DebugElement } from "@angular/core";
import { ComponentFixture } from "@angular/core/testing";
import { By } from "@angular/platform-browser";

import { GitHubGistInterface } from "./interfaces/github-gist.interface";
import { GitHubRepoInterface } from "./interfaces/github-repo.interface";
import { GitHubUserInterface } from "./interfaces/github-user.interface";

export class GitHubTestHelper<T> {
  constructor(private fixture: ComponentFixture<T>) {}

  /* DOM HELPING METHODS */
  public countElements(cssQuery: string): number {
    return this.fixture.debugElement.queryAll(By.css(cssQuery)).length
  }

  public getFirstElement(cssQuery: string): DebugElement {
    return this.fixture.debugElement.query(By.css(cssQuery));
  }

  public getAllElements(cssQuery: string): DebugElement[] {
    return this.fixture.debugElement.queryAll(By.css(cssQuery));
  }

  /* MOCKED DUMMY CONSTANTS */
  public static dummyGithubUser: GitHubUserInterface = {
    login: "DanielTamargo",
    id: 32647764,
    node_id: "MDQ6VXNlcjMyNjQ3NzY0",
    avatar_url: "https://avatars.githubusercontent.com/u/32647764?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/DanielTamargo",
    html_url: "https://github.com/DanielTamargo",
    followers_url: "https://api.github.com/users/DanielTamargo/followers",
    following_url: "https://api.github.com/users/DanielTamargo/following{/other_user}",
    gists_url: "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
    starred_url: "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/DanielTamargo/subscriptions",
    organizations_url: "https://api.github.com/users/DanielTamargo/orgs",
    repos_url: "https://api.github.com/users/DanielTamargo/repos",
    events_url: "https://api.github.com/users/DanielTamargo/events{/privacy}",
    received_events_url: "https://api.github.com/users/DanielTamargo/received_events",
    type: "User",
    site_admin: false,
    name: "Daniel Tamargo",
    company: null,
    blog: "",
    location: null,
    email: null,
    hireable: null,
    bio: null,
    twitter_username: null,
    public_repos: 18,
    public_gists: 3,
    followers: 0,
    following: 2,
    created_at: "2017-10-09T16:49:15Z",
    updated_at: "2022-04-30T08:20:53Z"
  }

  public static dummyGitHubRepos: GitHubRepoInterface[] = [
    {
      id: 478032792,
      node_id: "R_kgDOHH4zmA",
      name: "angular-app",
      full_name: "DanielTamargo/angular-app",
      private: false,
      owner: {
        login: "DanielTamargo",
        id: 32647764,
        node_id: "MDQ6VXNlcjMyNjQ3NzY0",
        avatar_url: "https://avatars.githubusercontent.com/u/32647764?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/DanielTamargo",
        html_url: "https://github.com/DanielTamargo",
        followers_url: "https://api.github.com/users/DanielTamargo/followers",
        following_url: "https://api.github.com/users/DanielTamargo/following{/other_user}",
        gists_url: "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
        starred_url: "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/DanielTamargo/subscriptions",
        organizations_url: "https://api.github.com/users/DanielTamargo/orgs",
        repos_url: "https://api.github.com/users/DanielTamargo/repos",
        events_url: "https://api.github.com/users/DanielTamargo/events{/privacy}",
        received_events_url: "https://api.github.com/users/DanielTamargo/received_events",
        type: "User",
        site_admin: false
      },
      html_url: "https://github.com/DanielTamargo/angular-app",
      description: "Aplicación creada para aprender y mejorar con Angular. Se dará uso de Angular, RxJS, Firebase, Angular Material, Bootstrap y Sass.",
      fork: false,
      url: "https://api.github.com/repos/DanielTamargo/angular-app",
      forks_url: "https://api.github.com/repos/DanielTamargo/angular-app/forks",
      keys_url: "https://api.github.com/repos/DanielTamargo/angular-app/keys{/key_id}",
      collaborators_url: "https://api.github.com/repos/DanielTamargo/angular-app/collaborators{/collaborator}",
      teams_url: "https://api.github.com/repos/DanielTamargo/angular-app/teams",
      hooks_url: "https://api.github.com/repos/DanielTamargo/angular-app/hooks",
      issue_events_url: "https://api.github.com/repos/DanielTamargo/angular-app/issues/events{/number}",
      events_url: "https://api.github.com/repos/DanielTamargo/angular-app/events",
      assignees_url: "https://api.github.com/repos/DanielTamargo/angular-app/assignees{/user}",
      branches_url: "https://api.github.com/repos/DanielTamargo/angular-app/branches{/branch}",
      tags_url: "https://api.github.com/repos/DanielTamargo/angular-app/tags",
      blobs_url: "https://api.github.com/repos/DanielTamargo/angular-app/git/blobs{/sha}",
      git_tags_url: "https://api.github.com/repos/DanielTamargo/angular-app/git/tags{/sha}",
      git_refs_url: "https://api.github.com/repos/DanielTamargo/angular-app/git/refs{/sha}",
      trees_url: "https://api.github.com/repos/DanielTamargo/angular-app/git/trees{/sha}",
      statuses_url: "https://api.github.com/repos/DanielTamargo/angular-app/statuses/{sha}",
      languages_url: "https://api.github.com/repos/DanielTamargo/angular-app/languages",
      stargazers_url: "https://api.github.com/repos/DanielTamargo/angular-app/stargazers",
      contributors_url: "https://api.github.com/repos/DanielTamargo/angular-app/contributors",
      subscribers_url: "https://api.github.com/repos/DanielTamargo/angular-app/subscribers",
      subscription_url: "https://api.github.com/repos/DanielTamargo/angular-app/subscription",
      commits_url: "https://api.github.com/repos/DanielTamargo/angular-app/commits{/sha}",
      git_commits_url: "https://api.github.com/repos/DanielTamargo/angular-app/git/commits{/sha}",
      comments_url: "https://api.github.com/repos/DanielTamargo/angular-app/comments{/number}",
      issue_comment_url: "https://api.github.com/repos/DanielTamargo/angular-app/issues/comments{/number}",
      contents_url: "https://api.github.com/repos/DanielTamargo/angular-app/contents/{+path}",
      compare_url: "https://api.github.com/repos/DanielTamargo/angular-app/compare/{base}...{head}",
      merges_url: "https://api.github.com/repos/DanielTamargo/angular-app/merges",
      archive_url: "https://api.github.com/repos/DanielTamargo/angular-app/{archive_format}{/ref}",
      downloads_url: "https://api.github.com/repos/DanielTamargo/angular-app/downloads",
      issues_url: "https://api.github.com/repos/DanielTamargo/angular-app/issues{/number}",
      pulls_url: "https://api.github.com/repos/DanielTamargo/angular-app/pulls{/number}",
      milestones_url: "https://api.github.com/repos/DanielTamargo/angular-app/milestones{/number}",
      notifications_url: "https://api.github.com/repos/DanielTamargo/angular-app/notifications{?since,all,participating}",
      labels_url: "https://api.github.com/repos/DanielTamargo/angular-app/labels{/name}",
      releases_url: "https://api.github.com/repos/DanielTamargo/angular-app/releases{/id}",
      deployments_url: "https://api.github.com/repos/DanielTamargo/angular-app/deployments",
      created_at: "2022-04-05T08:10:17Z",
      updated_at: "2022-04-26T07:51:53Z",
      pushed_at: "2022-04-27T06:39:36Z",
      git_url: "git://github.com/DanielTamargo/angular-app.git",
      ssh_url: "git@github.com:DanielTamargo/angular-app.git",
      clone_url: "https://github.com/DanielTamargo/angular-app.git",
      svn_url: "https://github.com/DanielTamargo/angular-app",
      homepage: "",
      size: 2840,
      stargazers_count: 0,
      watchers_count: 0,
      language: "TypeScript",
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: "public",
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: "main"
    },
    {
      id: 298891859,
      node_id: "MDEwOlJlcG9zaXRvcnkyOTg4OTE4NTk=",
      name: "arkanoid-unity",
      full_name: "DanielTamargo/arkanoid-unity",
      private: false,
      owner: {
        login: "DanielTamargo",
        id: 32647764,
        node_id: "MDQ6VXNlcjMyNjQ3NzY0",
        avatar_url: "https://avatars.githubusercontent.com/u/32647764?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/DanielTamargo",
        html_url: "https://github.com/DanielTamargo",
        followers_url: "https://api.github.com/users/DanielTamargo/followers",
        following_url: "https://api.github.com/users/DanielTamargo/following{/other_user}",
        gists_url: "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
        starred_url: "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/DanielTamargo/subscriptions",
        organizations_url: "https://api.github.com/users/DanielTamargo/orgs",
        repos_url: "https://api.github.com/users/DanielTamargo/repos",
        events_url: "https://api.github.com/users/DanielTamargo/events{/privacy}",
        received_events_url: "https://api.github.com/users/DanielTamargo/received_events",
        type: "User",
        site_admin: false
      },
      html_url: "https://github.com/DanielTamargo/arkanoid-unity",
      description: "Juego Arkanoid desarrollado en Unity con Firebase Realtime para almacenar las puntuaciones de los usuarios.",
      fork: false,
      url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity",
      forks_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/forks",
      keys_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/keys{/key_id}",
      collaborators_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/collaborators{/collaborator}",
      teams_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/teams",
      hooks_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/hooks",
      issue_events_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/issues/events{/number}",
      events_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/events",
      assignees_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/assignees{/user}",
      branches_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/branches{/branch}",
      tags_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/tags",
      blobs_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/git/blobs{/sha}",
      git_tags_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/git/tags{/sha}",
      git_refs_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/git/refs{/sha}",
      trees_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/git/trees{/sha}",
      statuses_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/statuses/{sha}",
      languages_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/languages",
      stargazers_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/stargazers",
      contributors_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/contributors",
      subscribers_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/subscribers",
      subscription_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/subscription",
      commits_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/commits{/sha}",
      git_commits_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/git/commits{/sha}",
      comments_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/comments{/number}",
      issue_comment_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/issues/comments{/number}",
      contents_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/contents/{+path}",
      compare_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/compare/{base}...{head}",
      merges_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/merges",
      archive_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/{archive_format}{/ref}",
      downloads_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/downloads",
      issues_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/issues{/number}",
      pulls_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/pulls{/number}",
      milestones_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/milestones{/number}",
      notifications_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/notifications{?since,all,participating}",
      labels_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/labels{/name}",
      releases_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/releases{/id}",
      deployments_url: "https://api.github.com/repos/DanielTamargo/arkanoid-unity/deployments",
      created_at: "2020-09-26T20:10:31Z",
      updated_at: "2022-03-30T08:21:48Z",
      pushed_at: "2020-09-26T20:11:52Z",
      git_url: "git://github.com/DanielTamargo/arkanoid-unity.git",
      ssh_url: "git@github.com:DanielTamargo/arkanoid-unity.git",
      clone_url: "https://github.com/DanielTamargo/arkanoid-unity.git",
      svn_url: "https://github.com/DanielTamargo/arkanoid-unity",
      homepage: "",
      size: 67096,
      stargazers_count: 0,
      watchers_count: 0,
      language: "C#",
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: {
        key: "apache-2.0",
        name: "Apache License 2.0",
        spdx_id: "Apache-2.0",
        url: "https://api.github.com/licenses/apache-2.0",
        node_id: "MDc6TGljZW5zZTI="
      },
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: "public",
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: "master"
    }
  ]

  public static dummyGitHubGists: GitHubGistInterface[] = [
    {
      url: "https://api.github.com/gists/7122b4f381cccba08cf71ced380c4623",
      forks_url: "https://api.github.com/gists/7122b4f381cccba08cf71ced380c4623/forks",
      commits_url: "https://api.github.com/gists/7122b4f381cccba08cf71ced380c4623/commits",
      id: "7122b4f381cccba08cf71ced380c4623",
      node_id: "G_kwDOAfIqVNoAIDcxMjJiNGYzODFjY2NiYTA4Y2Y3MWNlZDM4MGM0NjIz",
      git_pull_url: "https://gist.github.com/7122b4f381cccba08cf71ced380c4623.git",
      git_push_url: "https://gist.github.com/7122b4f381cccba08cf71ced380c4623.git",
      html_url: "https://gist.github.com/7122b4f381cccba08cf71ced380c4623",
      files: {
        "web-component.md": {
          filename: "web-component.md",
          type: "text/markdown",
          language: "Markdown",
          raw_url: "https://gist.githubusercontent.com/DanielTamargo/7122b4f381cccba08cf71ced380c4623/raw/b9f065c90087311acf6e09c37cd103c8c9bc7d4e/button-panel.md",
          size: 5645
        }
      },
      public: true,
      created_at: "2022-02-07T09:37:57Z",
      updated_at: "2022-05-02T10:10:57Z",
      description: "Código Web Component en JavaScript plano",
      comments: 0,
      user: null,
      comments_url: "https://api.github.com/gists/7122b4f381cccba08cf71ced380c4623/comments",
      owner: {
        login: "DanielTamargo",
        id: 32647764,
        node_id: "MDQ6VXNlcjMyNjQ3NzY0",
        avatar_url: "https://avatars.githubusercontent.com/u/32647764?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/DanielTamargo",
        html_url: "https://github.com/DanielTamargo",
        followers_url: "https://api.github.com/users/DanielTamargo/followers",
        following_url: "https://api.github.com/users/DanielTamargo/following{/other_user}",
        gists_url: "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
        starred_url: "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/DanielTamargo/subscriptions",
        organizations_url: "https://api.github.com/users/DanielTamargo/orgs",
        repos_url: "https://api.github.com/users/DanielTamargo/repos",
        events_url: "https://api.github.com/users/DanielTamargo/events{/privacy}",
        received_events_url: "https://api.github.com/users/DanielTamargo/received_events",
        type: "User",
        site_admin: false
      },
      truncated: false
    },
    {
      url: "https://api.github.com/gists/bc3c06fd824da7d5ea0569d3bf871839",
      forks_url: "https://api.github.com/gists/bc3c06fd824da7d5ea0569d3bf871839/forks",
      commits_url: "https://api.github.com/gists/bc3c06fd824da7d5ea0569d3bf871839/commits",
      id: "bc3c06fd824da7d5ea0569d3bf871839",
      node_id: "G_kwDOAfIqVNoAIGJjM2MwNmZkODI0ZGE3ZDVlYTA1NjlkM2JmODcxODM5",
      git_pull_url: "https://gist.github.com/bc3c06fd824da7d5ea0569d3bf871839.git",
      git_push_url: "https://gist.github.com/bc3c06fd824da7d5ea0569d3bf871839.git",
      html_url: "https://gist.github.com/bc3c06fd824da7d5ea0569d3bf871839",
      files: {
        "selectores-CSS-basicos-y-habituales.md": {
          filename: "selectores-CSS-basicos-y-habituales.md",
          type: "text/markdown",
          language: "Markdown",
          raw_url: "https://gist.githubusercontent.com/DanielTamargo/bc3c06fd824da7d5ea0569d3bf871839/raw/6e5a856779ad376e0a624e55c59577839f59d5de/selectores-CSS-basicos-y-habituales.md",
          size: 1619
        }
      },
      public: true,
      created_at: "2022-03-26T09:30:03Z",
      updated_at: "2022-04-07T08:08:11Z",
      description: "Algunos selectores CSS básicos",
      comments: 0,
      user: null,
      comments_url: "https://api.github.com/gists/bc3c06fd824da7d5ea0569d3bf871839/comments",
      owner: {
        login: "DanielTamargo",
        id: 32647764,
        node_id: "MDQ6VXNlcjMyNjQ3NzY0",
        avatar_url: "https://avatars.githubusercontent.com/u/32647764?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/DanielTamargo",
        html_url: "https://github.com/DanielTamargo",
        followers_url: "https://api.github.com/users/DanielTamargo/followers",
        following_url: "https://api.github.com/users/DanielTamargo/following{/other_user}",
        gists_url: "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
        starred_url: "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/DanielTamargo/subscriptions",
        organizations_url: "https://api.github.com/users/DanielTamargo/orgs",
        repos_url: "https://api.github.com/users/DanielTamargo/repos",
        events_url: "https://api.github.com/users/DanielTamargo/events{/privacy}",
        received_events_url: "https://api.github.com/users/DanielTamargo/received_events",
        type: "User",
        site_admin: false
      },
      truncated: false
    },
    {
      url: "https://api.github.com/gists/af07b0dc3870e6c04c5921220322bcc6",
      forks_url: "https://api.github.com/gists/af07b0dc3870e6c04c5921220322bcc6/forks",
      commits_url: "https://api.github.com/gists/af07b0dc3870e6c04c5921220322bcc6/commits",
      id: "af07b0dc3870e6c04c5921220322bcc6",
      node_id: "G_kwDOAfIqVNoAIGFmMDdiMGRjMzg3MGU2YzA0YzU5MjEyMjAzMjJiY2M2",
      git_pull_url: "https://gist.github.com/af07b0dc3870e6c04c5921220322bcc6.git",
      git_push_url: "https://gist.github.com/af07b0dc3870e6c04c5921220322bcc6.git",
      html_url: "https://gist.github.com/af07b0dc3870e6c04c5921220322bcc6",
      files: {
        "guia-laravel-8.md": {
          filename: "guia-laravel-8.md",
          type: "text/markdown",
          language: "Markdown",
          raw_url: "https://gist.githubusercontent.com/DanielTamargo/af07b0dc3870e6c04c5921220322bcc6/raw/ba5a20123700718746fe785a667d5de181836020/guia-laravel-8.md",
          size: 9879
        }
      },
      public: true,
      created_at: "2022-03-03T07:39:49Z",
      updated_at: "2022-04-07T06:50:00Z",
      description: "Una guía básica e intermedia de Laravel 8. Cómo crear y comenzar un proyecto.",
      comments: 0,
      user: null,
      comments_url: "https://api.github.com/gists/af07b0dc3870e6c04c5921220322bcc6/comments",
      owner: {
        login: "DanielTamargo",
        id: 32647764,
        node_id: "MDQ6VXNlcjMyNjQ3NzY0",
        avatar_url: "https://avatars.githubusercontent.com/u/32647764?v=4",
        gravatar_id: "",
        url: "https://api.github.com/users/DanielTamargo",
        html_url: "https://github.com/DanielTamargo",
        followers_url: "https://api.github.com/users/DanielTamargo/followers",
        following_url: "https://api.github.com/users/DanielTamargo/following{/other_user}",
        gists_url: "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
        starred_url: "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
        subscriptions_url: "https://api.github.com/users/DanielTamargo/subscriptions",
        organizations_url: "https://api.github.com/users/DanielTamargo/orgs",
        repos_url: "https://api.github.com/users/DanielTamargo/repos",
        events_url: "https://api.github.com/users/DanielTamargo/events{/privacy}",
        received_events_url: "https://api.github.com/users/DanielTamargo/received_events",
        type: "User",
        site_admin: false
      },
      truncated: false
    }
  ]

  public static dummyGithubRepoContributors: any[] = [
    {
      "login": "DanielTamargo",
      "id": 32647764,
      "node_id": "MDQ6VXNlcjMyNjQ3NzY0",
      "avatar_url": "https://avatars.githubusercontent.com/u/32647764?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielTamargo",
      "html_url": "https://github.com/DanielTamargo",
      "followers_url": "https://api.github.com/users/DanielTamargo/followers",
      "following_url": "https://api.github.com/users/DanielTamargo/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielTamargo/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielTamargo/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielTamargo/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielTamargo/orgs",
      "repos_url": "https://api.github.com/users/DanielTamargo/repos",
      "events_url": "https://api.github.com/users/DanielTamargo/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielTamargo/received_events",
      "type": "User",
      "site_admin": false,
      "contributions": 97
      }
  ]

  public static dummyGitHubEmptyRepo =
    {
      id: 1,
      node_id: "",
      name: "",
      full_name: "dummyRepo",
      private: false,
      owner: {
        login: "DanielTamargo",
        id: 1,
        node_id: "",
        avatar_url: "",
        gravatar_id: "",
        url: "",
        html_url: "",
        followers_url: "",
        following_url: "",
        gists_url: "",
        starred_url: "",
        subscriptions_url: "",
        organizations_url: "",
        repos_url: "",
        events_url: "",
        received_events_url: "",
        type: "",
        site_admin: false
      },
      html_url: "",
      description: "",
      fork: false,
      url: "",
      forks_url: "",
      keys_url: "",
      collaborators_url: "",
      teams_url: "",
      hooks_url: "",
      issue_events_url: "",
      events_url: "",
      assignees_url: "",
      branches_url: "",
      tags_url: "",
      blobs_url: "",
      git_tags_url: "",
      git_refs_url: "",
      trees_url: "",
      statuses_url: "",
      languages_url: "",
      stargazers_url: "",
      contributors_url: "",
      subscribers_url: "",
      subscription_url: "",
      commits_url: "",
      git_commits_url: "",
      comments_url: "",
      issue_comment_url: "",
      contents_url: "",
      compare_url: "",
      merges_url: "",
      archive_url: "",
      downloads_url: "",
      issues_url: "",
      pulls_url: "",
      milestones_url: "",
      notifications_url: "",
      labels_url: "",
      releases_url: "",
      deployments_url: "",
      created_at: "",
      updated_at: "",
      pushed_at: "",
      git_url: "",
      ssh_url: "",
      clone_url: "",
      svn_url: "",
      homepage: "",
      size: 1,
      stargazers_count: 0,
      watchers_count: 0,
      language: "",
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      forks_count: 0,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 0,
      license: null,
      allow_forking: true,
      is_template: false,
      topics: [],
      visibility: "",
      forks: 0,
      open_issues: 0,
      watchers: 0,
      default_branch: ""
    }


}
